[GENERAL]
EffectSearchPaths=.\reshade-shaders\Shaders
TextureSearchPaths=.\reshade-shaders\Textures
PresetPath=.\ReShadePreset.ini
PerformanceMode=1
SkipLoadingDisabledEffects=1
NoDebugInfo=0
NoEffectCache=0

[INPUT]
KeyOverlay=36,1,0,0
KeyEffects=145,0,0,0
KeyReload=145,1,0,0
GamepadNavigation=0
InputProcessing=2

[OVERLAY]
TutorialProgress=4
ShowFPS=0
ShowClock=0
ShowFrameTime=0
NoFontScaling=0
SaveWindowState=1

[SCREENSHOT]
SavePath=.\reshade-screenshots
SaveFormat=1
SaveOverlayShot=0
SaveBeforeShot=0
SaveSeparateNamingConvention=0
ClearAlpha=1
JPEGQuality=90
PostSaveCommand=
PostSaveCommandWorkingDirectory=
PostSaveCommandHideWindow=0

[STYLE]
StyleIndex=0
EditorStyleIndex=0
Font=ProggyClean.ttf
FontSize=13
EditorFont=ProggyClean.ttf
EditorFontSize=13

[DEPTH]
DepthCopyAtClearIndex=0
DepthCopyBeforeClears=0
DepthReversed=0
UseAspectRatioHeuristics=1

[ADDON]
DisabledAddons=
;
; Default preset (ReShadePreset.ini) enables SMAA + LumaSharpen + AmbientLight.
; Press Home in-game to open the ReShade overlay and toggle other effects;
; save your customized preset to override the defaults.
;
